version: '3'
services:
  ade-parser:
    image: 149.202.61.252:6000/ade-parser
    build:
      context: ./ade-parser
      dockerfile: Dockerfile

    volumes:
      - data:/usr/src/app/data

  api:
    image: 149.202.61.252:6000/api
    build:
      context: ./api
      dockerfile: Dockerfile

    volumes:
      - data:/usr/src/app/data

    expose:
      - 5000
    depends_on:
      - ade-parser
    deploy:
      labels:
        - "traefik.port=5000"
        - "traefik.backend=api"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:ade.wallforfry.fr"
    networks:
      - default
      - traefik-net

#  traefik:
#    image: traefik:latest
#    command: --api --docker --docker.swarmmode
#    ports:
#      - 80:80
#      - 8088:8080
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    deploy:
#      placement:
#        constraints:
#          - node.role == manager

volumes:
  data:

networks:
  traefik-net:
    external: true
