version: '3'
services:
  ade-parser:
    image: 149.202.61.252:6000/ade-parser
    build:
      context: ./ade-parser
      dockerfile: Dockerfile

    volumes:
      - data:/usr/src/app/data

  api:
    image: 149.202.61.252:6000/api
    build:
      context: ./api
      dockerfile: Dockerfile

    volumes:
      - data:/usr/src/app/data

    expose:
      - 5000
    depends_on:
      - ade-parser
    deploy:
      labels:
        - "traefik.port=5000"
        - "traefik.backend=api"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:ade.wallforfry.fr"
    networks:
      - default
      - traefik-net

volumes:
  data:

networks:
  traefik-net:
    external: true
