version: '3'
services:
  ade-parser:
    image: 149.202.61.252:6000/ade-parser
    build:
      context: ./ade-parser
      dockerfile: Dockerfile

    volumes:
      - data:/usr/src/app/data

  api:
    image: 149.202.61.252:6000/api
    build:
      context: ./api
      dockerfile: Dockerfile

    volumes:
      - data:/usr/src/app/data

    expose:
      - 5000
    depends_on:
      - ade-parser

  nginx:
    image: 149.202.61.252:6000/nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile

    ports:
      - 5000:80
    links:
      - api

volumes:
  data:
